// <auto-generated />
namespace SAFERUN.IMS.Web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.1-30610")]
    public sealed partial class ddd1 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ddd1));
        
        string IMigrationMetadata.Id
        {
            get { return "201603231400247_ddd1"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
